-- MySQL Script generated by MySQL Workbench
-- Thu Mar 23 00:19:27 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SPSUNews_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SPSUNews_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SPSUNews_database` DEFAULT CHARACTER SET utf8 ;
USE `SPSUNews_database` ;

-- -----------------------------------------------------
-- Table `SPSUNews_database`.`editor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPSUNews_database`.`editor` (
  `id_editor` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `fk_article_editor` INT NULL,
  PRIMARY KEY (`id_editor`),
  INDEX `fk_article_editor_idx` (`fk_article_editor` ASC),
  CONSTRAINT `fk_article_editor`
    FOREIGN KEY (`fk_article_editor`)
    REFERENCES `SPSUNews_database`.`article` (`id_article`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Таблица редакторов.';


-- -----------------------------------------------------
-- Table `SPSUNews_database`.`like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPSUNews_database`.`like` (
  `id_like` INT NOT NULL,
  `fk_article_like` INT NULL,
  `fk_user_like` INT NULL,
  `value` BINARY(2) NULL,
  PRIMARY KEY (`id_like`),
  INDEX `fk_article_like_idx` (`fk_article_like` ASC),
  INDEX `fk_user_like_idx` (`fk_user_like` ASC),
  CONSTRAINT `fk_article_like`
    FOREIGN KEY (`fk_article_like`)
    REFERENCES `SPSUNews_database`.`article` (`id_article`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_like`
    FOREIGN KEY (`fk_user_like`)
    REFERENCES `SPSUNews_database`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Таблица лайков';


-- -----------------------------------------------------
-- Table `SPSUNews_database`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPSUNews_database`.`article` (
  `id_article` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `date` DATE NOT NULL,
  `like` INT NULL,
  `content` TEXT NOT NULL,
  `image` MEDIUMBLOB NULL,
  `value_sum` INT NULL,
  `fk_editor_article` INT NULL,
  `fk_like_article` INT NULL,
  `fk_comment_article` INT NULL,
  PRIMARY KEY (`id_article`),
  INDEX `fk_editor_article_idx` (`fk_editor_article` ASC),
  INDEX `fk_like_article_idx` (`fk_like_article` ASC),
  INDEX `fk_comment_article_idx` (`fk_comment_article` ASC),
  CONSTRAINT `fk_editor_article`
    FOREIGN KEY (`fk_editor_article`)
    REFERENCES `SPSUNews_database`.`editor` (`id_editor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_like_article`
    FOREIGN KEY (`fk_like_article`)
    REFERENCES `SPSUNews_database`.`like` (`id_like`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_article`
    FOREIGN KEY (`fk_comment_article`)
    REFERENCES `SPSUNews_database`.`comment` (`id_comment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Таблица статей';


-- -----------------------------------------------------
-- Table `SPSUNews_database`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPSUNews_database`.`comment` (
  `id_comment` INT NOT NULL,
  `date` DATE NOT NULL,
  `text` TEXT NULL,
  `fk_article_comment` INT NULL,
  `fk_user_comment` INT NULL,
  PRIMARY KEY (`id_comment`),
  INDEX `fk_article_comment_idx` (`fk_article_comment` ASC),
  INDEX `fk_user_comment_idx` (`fk_user_comment` ASC),
  CONSTRAINT `fk_article_comment`
    FOREIGN KEY (`fk_article_comment`)
    REFERENCES `SPSUNews_database`.`article` (`id_article`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_comment`
    FOREIGN KEY (`fk_user_comment`)
    REFERENCES `SPSUNews_database`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Таблица комментария';


-- -----------------------------------------------------
-- Table `SPSUNews_database`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPSUNews_database`.`user` (
  `id_user` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NULL,
  `password` CHAR(64) NOT NULL,
  `fk_comment_user` INT NULL,
  `fk_like_user` INT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_comment_idx` (`fk_comment_user` ASC),
  INDEX `fk_like_user_idx` (`fk_like_user` ASC),
  CONSTRAINT `fk_comment_user`
    FOREIGN KEY (`fk_comment_user`)
    REFERENCES `SPSUNews_database`.`comment` (`id_comment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_like_user`
    FOREIGN KEY (`fk_like_user`)
    REFERENCES `SPSUNews_database`.`like` (`id_like`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Таблица пользователей';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
